sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

branches:
  only:
    master

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit
