sudo: false

language: php

env:
  global:
    - COMPOSER_DISCARD_CHANGES=1

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

branches:
  only:
    master

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit --coverage-clover=./clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./clover.xml

stages:
  - test
  - style check
  - phpstan analysis

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly

    - stage: style check
      php: 7.3
      script:
        - composer style-check

    - stage: phpstan analysis
      php: 7.3
      script:
        - composer phpstan
