sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

branches:
  only:
    master

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit --coverage-clover=./clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./clover.xml
